; electronics-lab — STM32F401CCU6 (WeAct Black Pill) experiments
; One env per experiment; build_src_filter selects that experiment's folder.

[env:exp01_rc_step]
platform = ststm32
board = blackpill_f401cc
framework = stm32cube
upload_protocol = stlink
upload_flags =
    -c
    set CPUTAPID 0
build_flags = -DDEBUG_ENABLED=1
monitor_speed = 115200
build_src_filter = -<*> +<exp01_rc_step/>

[env:exp02_dht11]
platform = ststm32
board = blackpill_f401cc
framework = stm32cube
upload_protocol = stlink
upload_flags =
    -c
    set CPUTAPID 0
build_flags = -DDEBUG_ENABLED=1
monitor_speed = 115200
build_src_filter = -<*> +<exp02_dht11/>

[env:exp06_transistor_led]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
upload_flags =
    -c
    set CPUTAPID 0
build_src_filter = -<*> +<exp06_transistor_led/>

[env:exp07a_led_pattern]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
upload_flags =
    -c
    set CPUTAPID 0
build_src_filter = -<*> +<exp07a_led_pattern/>

[env:exp07a_pb0]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
upload_protocol = stlink
upload_flags =
    -c
    set CPUTAPID 0
build_flags = -DPWM_OUT=PWM_OUT_PB0
build_src_filter = -<*> +<exp07a_led_pattern/>
